### ISSUE TITLE
PIRB Rerankers results reproduction

### ISSUE THREAD

**Issue by BorisFlu** [sdadas/pirb#1]
Would it be possible to add as an example, the model configuration as well as the script parameters used to reproduce the results obtained in the in the **Rerankers** section of the [PIRB](https://huggingface.co/spaces/sdadas/pirb) with your [polish-reranker-large-ranknet](https://huggingface.co/sdadas/polish-reranker-large-ranknet)  please?

It seems that I have some score discrepancies using the following configuration:

```json
[
  {
    "name": "polish-reranker-large-ranknet",
    "type": "hybrid",
    "k0": 100,
    "strategy": {
      "type": "reranker",
      "reranker_name": "sdadas/polish-reranker-large-ranknet",
      "reranker_type": "classifier",
      "batch_size": 32,
      "fp16": false,
      "template": "{query}{sep}{sep}{passage}"
    },
    "models": [
      {
        "name": "sdadas/mmlw-retrieval-roberta-large",
        "fp16": true,
        "q_prefix": "zapytanie: "
      }
    ]
  }
]
```
along with
`run_benchmark.py --models_config "${MODEL_CONFIG_PATH}" --data_dir "${DATA_DIR}" --cache_dir "${CACHE_DIR}" --scope full --query_limit 1000`

(I also tried without the query limit)

Thanks in advance!

**Comment by sdadas** [comment]
Hi, the configurations for each reranker are in the config/rerankers directory. Your configuration is almost identical to the one we used - the only difference is the `bf16` precision.
Could you provide some examples of datasets on which you found the discrepancies and your scores on those datasets?

**Comment by BorisFlu** [comment]
Oh nice, I missed the configuration update thanks!
I will give it a try with the bf16.
On average the scores are lower on my side, but one of the most impacted score is the NDCG@10 for MFAQ

**Comment by sdadas** [comment]
I recomputed the results for the MFAQ dataset using the latest versions of sentence-transformers (2.6.1) and HF transformers (4.39.3). 
I ran the evaluation four times and got the following NDCG@10 scores: 72.97, 73.23, 72.98, 73.21. I'm not sure why the results are not identical each time, but they are still very close to the leaderboard (73.06).

**Comment by BorisFlu** [comment]
After updating, my environment I do find the same results. Thank you for your responsiveness!
